spring:
  application:
    name: "eurekaserver"

#    config-server related
  config:
    import: "optional:configserver:http://localhost:8071/"

#actuator related properties and health check
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true